#ifndef SPACEINVADERS_GAMECONSTANTS_H
#define SPACEINVADERS_GAMECONSTANTS_H

#include <chrono>

const int DEFAULT_SCREEN_WIDTH = 1000;
const int DEFAULT_SCREEN_HEIGHT = 700;

const int MAX_LIVES = 3;

const int SCREEN_FPS = 60;
const auto SCREEN_TIME = std::chrono::milliseconds(1000/SCREEN_FPS);

enum EVENT {CTRL_QUIT, CTRL_IDLE, CTRL_LEFT, CTRL_RIGHT, CTRL_SHOOT};

enum ENTITY {PLAYERSHIP, ENEMYSHIP0, ENEMYSHIP1, ENEMYSHIP2, ENEMYSHIP3, ENEMYSHIP4, PLAYERBULLET, ENEMYBULLET};

const float PLAYER_SPEED = 0.5;
const float NORMALISED_SPEED = PLAYER_SPEED/ SCREEN_FPS;

const float BULLET_SPEED = 1;
const float NORMALISED_BULLET_SPEED = BULLET_SPEED/ SCREEN_FPS;

const float PLAYERSHIP_WIDTH = 0.05;
const float PLAYERSHIP_HEIGHT = 0.05;

const float ENEMYSHIP_WIDHT = 0.05;
const float ENEMYSHIP_HEIGHT = 0.05;

const float BULLET_WIDTH = 0.005;
const float BULLET_HEIGHT = 0.03;

const float ENEMY_COOLDOWN = 1; // Cooldown in seconds
const int NORMALIZED_ENEMY_COOLDOWN = ENEMY_COOLDOWN * SCREEN_FPS;

#endif
