#ifndef SPACEINVADERS_GAMECONSTANTS_H
#define SPACEINVADERS_GAMECONSTANTS_H

const int DEFAULT_SCREEN_WIDTH = 1000;
const int DEFAULT_SCREEN_HEIGHT = 700;

const int SCREEN_FPS = 60;
const int SCREEN_TICK_PER_FRAME = 1000 / SCREEN_FPS;

enum EVENT {CTRL_QUIT, CTRL_IDLE, CTRL_LEFT, CTRL_RIGHT, CTRL_SHOOT};

const int PLAYERSHIP = 10;
const int ENEMYSHIP = 11;

const float PLAYER_SPEED = 1.5;
const float NORMALISED_SPEED = PLAYER_SPEED/ SCREEN_FPS;

#endif