#ifndef SPACEINVADERS_ENUMS_H
#define SPACEINVADERS_ENUMS_H

// Enumerators
enum EVENT {
    CTRL_QUIT, CTRL_LEFT, CTRL_RIGHT, CTRL_SHOOT
};

enum ENTITY {
    PLAYERSHIP,
    ENEMYSHIP0,
    ENEMYSHIP1,
    ENEMYSHIP2,
    ENEMYSHIP3,
    ENEMYSHIP4,
    ENEMY_WRECK,
    PLAYER_WRECK,
    PLAYERBULLET,
    ENEMYBULLET,
    POSBONUS,
    NEGBONUS
};

enum SOUND {
    EXPLOSION, INVADER_KILLED, SHOOT, HIT, LOSS, VICTORY, BONUS_SPAWN
};

#endif
